export const POST_UPDATE = "POST_UPDATE";
export const NEW_POST_CREATION = "NEW_POST_CREATION";
export const POST_REMOVAL = "POST_REMOVAL";

export const NEW_POST_COMMENT = "NEW_POST_COMMENT";
export const POST_COMMENT_UPDATE = "POST_COMMENT_UPDATE";
export const POST_COMMENT_REMOVAL = "POST_COMMENT_REMOVAL";
